config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/show" ,to: "users#show", as:"show"

  get "/signup" ,to: "users#new_signup", as:"sign_up"
  post "/signup" ,to: "users#signup", as:"user_signup"
  get "/login" ,to: "users#new_login", as:"login"
  get "/about" ,to: "users_contact#about", as:"about"
  get "/news" ,to: "users_contact#news", as:"news"

  post "/login" ,to: "users#login", as:"user_login"
  get "/contact" ,to: "users_contact#new_contact", as:"contact"
  post "/contact" ,to: "users_contact#contact", as:"user_contact"
  match '/logout(/:id)', to: "users#destroy", as: "user_logout", via: [:get, :delete]
  
  get "/new" ,to: "questions#new", as:"new_question"
  post "/create" ,to: "questions#create", as:"create_question"
  get "/index" ,to: "questions#index", as:"show_question"
  delete "/destroy/:id" , to: "questions#delete_question" , as: "delete_question"
  get "/generate_pdf" ,to: "questions#generate_pdf", as:"generate_pdf"

  
  resources :passwords, only: [:new, :create, :edit, :update]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_contacts, dependent: :destroy
  has_many :questions , dependent: :destroy
  has_secure_password 

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true ,
   uniqueness: { case_sensitive: false },
    length: { maximum: 105 },
    format: { with: VALID_EMAIL_REGEX }
  validate :passwords_match
  validates :username, presence: true ,uniqueness: :true
  validates :password, presence: true ,confirmation: { case_sensitive: true } , length: { minimum: 8 }
  validate :password_complexity
  validates_confirmation_of :password

  def generate_password_reset_token
    self.password_reset_token = SecureRandom.urlsafe_base64
    self.password_reset_sent_at = Time.now
    save!(validate: false)
  end

  def reset_password!(new_password)
    self.password_reset_token = nil
    self.password_reset_sent_at = nil
    self.password = new_password
    save!
  end
  
  private
  def password_complexity
    return unless password
  
    unless password.match?(/\A(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]+\z/)
      errors.add(:password, "must include at least one lowercase letter, one uppercase letter, one digit, and one special character")
    end
  end


  def passwords_match
    if password.present? && password_confirmation.present? && password != password_confirmation
      errors.add(:password, "and password confirmation must match")
    end
  end
end

app/models/user_contact.rb
class UserContact < ApplicationRecord
    belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController

	def new
		render :new
	end

	def create
		# binding.irb
		user = User.find_by(email: params[:email])
		if user
			user.generate_password_reset_token
			UserMailer.password_reset_email(user).deliver_now
			flash[:notice] = "Password reset instructions have been sent to your email."
			redirect_to login_path
		else
			# binding.irb
			redirect_to new_password_path
			flash[:error] = "User not found with the provided email."
			# render :new
		end
	end

	def edit
		# render the password reset form
	end

	def update
		user = User.find_by(password_reset_token: params[:token])
		if user && user.password_reset_sent_at > 20.minute.ago
			user.reset_password!(params[:password])
			flash[:success] = "Password has been reset successfully."
			redirect_to login_path
		else
			flash[:error] = "Password reset link has expired."
			render :edit
		end
	end
end
  

app/controllers/questions_controller.rb
require 'prawn'
class QuestionsController < ApplicationController

	before_action :current_user

	def new
		@question = Question.new
	end

	def create
		@question = Question.new(question_params.merge(user_id: @user.id))
		if @question.save
			flash[:success] = "Question sucessfuly Add!"
			redirect_to show_question_path
		else
			render :new
		end
	end

	def index
		@question = Question.where(user_id: session[:user_id])
	end

	def generate_pdf
		marks = params[:marks].to_i
		user = current_user
		pages = (marks / 50).to_i 
		pdf = Prawn::Document.new
		pdf.text "Question Paper\n\n"
		pages.times do |page_number|
			pdf.start_new_page if page_number > 0
			pdf.text "Page #{page_number + 1}"
		end
		filename = "question_paper_#{user.id}_#{marks}.pdf"
		pdf.render_file(Rails.root.join('public', 'pdfs', filename))
		send_data pdf.render, filename: filename, type: "application/pdf", disposition: "inline"
	end
	
	
	def current_user
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    else
      redirect_to login_path
      flash[:error] = "Must be login"
    end
  end
	
	def delete_question
    @question = Question.find(params[:id])
		@question.destroy
		flash[:success] = "Question sucessfuly Deleted"
		redirect_to show_question_path
	end

	private
	def question_params
		params.require(:question).permit(:question, :marks)
	end
end
  

app/controllers/users_contact_controller.rb
class UsersContactController < ApplicationController
	before_action :current_user

	def new_contact
		@user_contact = UserContact.new
	end
	def contact
		@user = UserContact.new(contact_params.merge(user_id: @user.id))
		if @user.save
			flash[:success] = "Message has been sent we will reach you soon !"
			redirect_to contact_path
		else
			flash[:error] = @user.errors.full_messages
			redirect_to contact_path

		end
	end

	def about
	end

	def news
	end

	def current_user
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    else
      redirect_to login_path
      flash[:error] = "Must be login"
    end
  end

	private
	def contact_params
		params.require(:user_contact).permit(:name, :contact, :message)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
	def index
	end

	def show
		@user = User.find(session[:user_id])
	end

	def new_signup
		@user = User.new
	end

	def signup
		# binding.irb
		@user = User.new(user_params)
		if @user.save
			UserMailer.welcome_email(@user).deliver_now
			flash[:success] = "Account sucessfuly created"
			redirect_to login_path
		else
			flash[:error] = @user.errors.full_messages
			redirect_to sign_up_path
		end
	end

	def new_login
		@user = User.new
	end

	def login
	  @user = User.find_by_username(params[:user][:username])
		if @user && @user.authenticate(params[:user][:password])
			session[:user_id] = @user.id
			flash[:success] = "Logged in Sucessfully!"
			redirect_to show_path
		else
			flash[:error] ='Invalid username/password combination'
			redirect_to login_path
		end
	end

	def destroy
		if params[:id].present?
			session[:user_id] = nil
			flash[:notice] = 'User  successfully logged out.'
		end
		redirect_to root_path
	end

	def current_user
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    else
      redirect_to login_path
      flash[:error] = "Must be login"
    end
  end

	private
	def user_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_contact_helper.rb
module UsersContactHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Generate Pdf App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <% flash.each do |key, message| %>
      <div class="flash <%= key %>">
        <%= message %>
      </div>
    <% end %>
  </body>
</html>
9111115752

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
      ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #333;
      }

      li {
        float: left;
      }

      li a {
        display: block;
        color: white;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
      }

      li a:hover {
        background-color: #111;
      }
    </style>
  </head>
  <body>
  <ul>

  <% if session[:user_id] %>
      <li style="color: white;">
      Logged in as <strong><%= @user.username %></strong>.
      <%= link_to 'Logout', user_logout_path(@user), method: :delete %>
      </li>
      <li><a class="active" ></a></li>
      <li><%= link_to 'Home',show_path %></li>
      <li><%= link_to 'News',news_path %></li>
      <li><%= link_to 'About',about_path %></li>
      <li><%= link_to 'Contact Us', contact_path %></li>
      <li><%= link_to 'Add Question', new_question_path %></li>
      <li><%= link_to 'Show Question', show_question_path %></li>

    <% else %>
      <li><a class="active"></a></li>
      <li><%= link_to 'Home',root_path %></li>
      <li><%= link_to 'News',news_path %></li>
      <li><%= link_to 'Contact Us' , contact_path%></li>
      <li><%= link_to 'About',about_path%></li>
      <li><%= link_to 'Signup', sign_up_path %></li>
      <li><%= link_to 'Login', login_path %></li>
      <li><%= link_to 'Add Question', new_question_path %></li>


    <% end %>
  </ul>
  
  </body>
</html>

app/views/questions/index.html.erb
<%= render partial: 'partials/header' %>

<!DOCTYPE html>
<html>
<head>
<style>
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }
  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }
  tr:nth-child(even) {
    background-color: #dddddd;
  }
</style>
</head>
<body>
<h1>Questions Details</h1>
<table>
  <tr>
    <th>Question</th>
    <th>Marks</th>
    <th>Actions</th>
  </tr>

  <% @question.each do |question| %>
    <tr>
      <td><%= question.question %></td>
      <td><%= question.marks %></td>
      <td><%=  button_to 'Delete', delete_question_path(question),method: :delete %><br><%= link_to 'Generate PDF', generate_pdf_path(marks: question.marks), method: :get, class: 'btn btn-primary' %>
     
      </td>
    </tr>
  <% end %>
</table>
</body>
</html>

app/views/questions/new.html.erb
<%= render partial: 'partials/header' %>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    *{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    display: flex;
    height: 100vh;
    background-color: #343a40;
}
#container{
    margin:auto;
    display: flex;
    color:#f8f9fa;
    flex-direction: column;
    width:500px;
    box-shadow: 1px 2px 71px -6px rgba(0,0,0,0.67);
    height:fit-content;
    font-family:sans-serif;
    background-color: #212529;
    padding:25px 20px;
    border-radius: 10px;
}
#Heading{
    padding:15px;
    text-align: center;
    font-size: 2.5em;
    font-weight: 900;
}
label{
    font-size: 1.1em;
    font-weight: 500;
    margin:10px 0px;
}
input{
    padding:10px;
    border-top-right-radius: 10px;
    height: 50px;
    background-color: #6c757d;
    border-bottom-right-radius:10px;
    outline: none;
    border: none;
    font-size:19px;
    transition-duration: 0.15s;
    
    color:#f8f9fa;
}
input:focus{
    outline: none;
    background-color: none;
}
input::placeholder{
    color:#f8f9fa;
    font-size: 19.2px;
}
.row:not(.name){
    width:100%;
    height:fit-content;
    display: grid;
    grid-template-columns: 10% 90%;
    grid-template-rows: 50px;
}
.name{
    width:100%;
    height: fit-content;
    display: flex;
    margin-top:20px;

}
.name>input{
    width:calc(50% - 5px);
    margin:5px;
    border-radius: 10px;;
}
.icon{
    height: 50px;
    background-color: #6c757d;
    border-top-left-radius: 10px;
    padding:10px;
    margin-right:1px;
    border-bottom-left-radius: 10px;
    fill:white;
}
button{
    width:fit-content;
    margin:20px auto;
    padding:10px 20px;
    outline: none;
    border: none;
    border-radius: 20px;
    font-weight: 700;
    color:white;
    background-color: #248277;
    font-family:sans-serif;
    font-size: 1.1em;
    cursor: pointer;
    transition-duration: 0.25s;
}
button:hover{
    background-color: #036666;
}
span{
    display: flex;
    justify-content: flex-end;

}
a{
    text-decoration: none;
    color:#99e2b4;
}
span>span>a{
    margin:0px 5px
}
a:hover{
    color: #06d6a0;
}
#MsgBx{
    width:100%;
    position: absolute;
    top:0px;
    left:0px;
    height:auto;
    padding:20px;
}
#MsgBx>li{
    list-style: none;
    color: white;
    border-radius: 5px;
    padding:10px;
    background-color: #036666;
    width:fit-content;
    font-family: 'Ubuntu', sans-serif;
    position: relative;
    animation: enteranceError 1s ease;
    margin:5px;
}
input:focus{
    border:5px solid #06d6a0;
    height: 49px;
    margin-top:2px;
}

</style>
<body>
<%= form_with(model: @question, url: create_question_path, method: :post) do |form| %>
  <h3 id="Heading">New Question</h3>

  <%= form.label :question %>
  <div class="row">
    <div class="icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" width="100%"><path d="M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z"/></svg></div>
    <%= form.text_field :question, placeholder: 'Question', required: true %>
  </div>
<br>
<div>
  <%= form.label :marks %>
  <div class="row">
    <div class="icon">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="100%">
        <path d="M488 80H24C10.75 80 0 90.75 0 104v304c0 13.25 10.75 24 24 24h464c13.25 0 24-10.75 24-24V104C512 90.75 501.3 80 488 80zM256 272L24 144h464L256 272z"/>
      </svg>
    </div>
    <%= form.select :marks, options_for_select([50,100, 150]), {}, required: true, placeholder: 'Choose Marks' %>
  </div>
</div>
<br>
<button type="submit">Submit</button>
<% end %>
</body>
</html>

app/views/users/index.html.erb
<%= render partial: 'partials/header' %>
<h1>This Is Home Page</h1>

app/views/users/new_login.html.erb
<%= render partial: 'partials/header' %>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    *{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    display: flex;
    height: 100vh;
    background-color: #343a40;
}
#container{
    margin:auto;
    display: flex;
    color:#f8f9fa;
    flex-direction: column;
    width:500px;
    box-shadow: 1px 2px 71px -6px rgba(0,0,0,0.67);
    height:fit-content;
    font-family:sans-serif;
    background-color: #212529;
    padding:25px 20px;
    border-radius: 10px;
}
#Heading{
    padding:15px;
    text-align: center;
    font-size: 2.5em;
    font-weight: 900;
}
label{
    font-size: 1.1em;
    font-weight: 500;
    margin:10px 0px;
}
input{
    padding:10px;
    border-top-right-radius: 10px;
    height: 50px;
    background-color: #6c757d;
    border-bottom-right-radius:10px;
    outline: none;
    border: none;
    font-size:19px;
    transition-duration: 0.15s;
    
    color:#f8f9fa;
}
input:focus{
    outline: none;
    background-color: none;
}
input::placeholder{
    color:#f8f9fa;
    font-size: 19.2px;
}
.row:not(.name){
    width:100%;
    height:fit-content;
    display: grid;
    grid-template-columns: 10% 90%;
    grid-template-rows: 50px;
}
.name{
    width:100%;
    height: fit-content;
    display: flex;
    margin-top:20px;

}
.name>input{
    width:calc(50% - 5px);
    margin:5px;
    border-radius: 10px;;
}
.icon{
    height: 50px;
    background-color: #6c757d;
    border-top-left-radius: 10px;
    padding:10px;
    margin-right:1px;
    border-bottom-left-radius: 10px;
    fill:white;
}
button{
    width:fit-content;
    margin:20px auto;
    padding:10px 20px;
    outline: none;
    border: none;
    border-radius: 20px;
    font-weight: 700;
    color:white;
    background-color: #248277;
    font-family:sans-serif;
    font-size: 1.1em;
    cursor: pointer;
    transition-duration: 0.25s;
}
button:hover{
    background-color: #036666;
}
span{
    display: flex;
    justify-content: flex-end;

}
a{
    text-decoration: none;
    color:#99e2b4;
}
span>span>a{
    margin:0px 5px
}
a:hover{
    color: #06d6a0;
}
#MsgBx{
    width:100%;
    position: absolute;
    top:0px;
    left:0px;
    height:auto;
    padding:20px;
}
#MsgBx>li{
    list-style: none;
    color: white;
    border-radius: 5px;
    padding:10px;
    background-color: #036666;
    width:fit-content;
    font-family: 'Ubuntu', sans-serif;
    position: relative;
    animation: enteranceError 1s ease;
    margin:5px;
}
input:focus{
    border:5px solid #06d6a0;
    height: 49px;
    margin-top:2px;
}

</style>
<body>
<%= form_with(model: @user, url: user_login_path) do |form| %>
  <h3 id="Heading">Login</h3>

  <%= form.label :username %>
  <div class="row">
    <div class="icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" width="100%"><path d="M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z"/></svg></div>
    <%= form.text_field :username, placeholder: 'Username', required: true %>
  </div>
  <br>
  <%= form.label :password %>
  <div class="row">
    <div class="icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="30px"><path d="M336 352c97.2 0 176-78.8 176-176S433.2 0 336 0S160 78.8 160 176c0 18.7 2.9 36.8 8.3 53.7L7 391c-4.5 4.5-7 10.6-7 17v80c0 13.3 10.7 24 24 24h80c13.3 0 24-10.7 24-24V448h40c13.3 0 24-10.7 24-24V384h40c6.4 0 12.5-2.5 17-7l33.3-33.3c16.9 5.4 35 8.3 53.7 8.3zM376 96a40 40 0 1 1 0 80 40 40 0 1 1 0-80z"/></svg></div>
    <%= form.password_field :password, placeholder: 'Password', required: true %>
  </div>
  <br>
  <button type="submit">Login</button>
  <%= link_to sign_up_path do %>
    <button type="button">Signup</button>
  <% end %>
  
  <br>
  <%= link_to 'Forgot Your Password ?', new_password_path %>

<% end %>
</body>
</html>

app/views/users/new_signup.html.erb
<%= render partial: 'partials/header' %>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    *{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    display: flex;
    height: 100vh;
    background-color: #343a40;
}
#container{
    margin:auto;
    display: flex;
    color:#f8f9fa;
    flex-direction: column;
    width:500px;
    box-shadow: 1px 2px 71px -6px rgba(0,0,0,0.67);
    height:fit-content;
    font-family:sans-serif;
    background-color: #212529;
    padding:25px 20px;
    border-radius: 10px;
}
#Heading{
    padding:15px;
    text-align: center;
    font-size: 2.5em;
    font-weight: 900;
}
label{
    font-size: 1.1em;
    font-weight: 500;
    margin:10px 0px;
}
input{
    padding:10px;
    border-top-right-radius: 10px;
    height: 50px;
    background-color: #6c757d;
    border-bottom-right-radius:10px;
    outline: none;
    border: none;
    font-size:19px;
    transition-duration: 0.15s;
    
    color:#f8f9fa;
}
input:focus{
    outline: none;
    background-color: none;
}
input::placeholder{
    color:#f8f9fa;
    font-size: 19.2px;
}
.row:not(.name){
    width:100%;
    height:fit-content;
    display: grid;
    grid-template-columns: 10% 90%;
    grid-template-rows: 50px;
}
.name{
    width:100%;
    height: fit-content;
    display: flex;
    margin-top:20px;

}
.name>input{
    width:calc(50% - 5px);
    margin:5px;
    border-radius: 10px;;
}
.icon{
    height: 50px;
    background-color: #6c757d;
    border-top-left-radius: 10px;
    padding:10px;
    margin-right:1px;
    border-bottom-left-radius: 10px;
    fill:white;
}
button{
    width:fit-content;
    margin:20px auto;
    padding:10px 20px;
    outline: none;
    border: none;
    border-radius: 20px;
    font-weight: 700;
    color:white;
    background-color: #248277;
    font-family:sans-serif;
    font-size: 1.1em;
    cursor: pointer;
    transition-duration: 0.25s;
}
button:hover{
    background-color: #036666;
}
span{
    display: flex;
    justify-content: flex-end;

}
a{
    text-decoration: none;
    color:#99e2b4;
}
span>span>a{
    margin:0px 5px
}
a:hover{
    color: #06d6a0;
}
#MsgBx{
    width:100%;
    position: absolute;
    top:0px;
    left:0px;
    height:auto;
    padding:20px;
}
#MsgBx>li{
    list-style: none;
    color: white;
    border-radius: 5px;
    padding:10px;
    background-color: #036666;
    width:fit-content;
    font-family: 'Ubuntu', sans-serif;
    position: relative;
    animation: enteranceError 1s ease;
    margin:5px;
}
input:focus{
    border:5px solid #06d6a0;
    height: 49px;
    margin-top:2px;
}

</style>
<body>
<%= form_with(model: @user, url: user_signup_path) do |form| %>
  <h3 id="Heading">Sign Up</h3>

  <%= form.label :username %>
  <div class="row">
    <div class="icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" width="100%"><path d="M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z"/></svg></div>
    <%= form.text_field :username, placeholder: 'Username', required: true %>
  </div>
  <br>
  
  <%= form.label :email %>
  <div class="row">
    <div class="icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="100%"><path d="M48 64C21.5 64 0 85.5 0 112c0 15.1 7.1 29.3 19.2 38.4L236.8 313.6c11.4 8.5 27 8.5 38.4 0L492.8 150.4c12.1-9.1 19.2-23.3 19.2-38.4c0-26.5-21.5-48-48-48H48zM0 176V384c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V176L294.4 339.2c-22.8 17.1-54 17.1-76.8 0L0 176z"/></svg></div>
    <%= form.email_field :email, placeholder: 'Email', required: true %>
  </div>
  <br>
  <%= form.label :password %>
  <div class="row">
    <div class="icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="30px"><path d="M336 352c97.2 0 176-78.8 176-176S433.2 0 336 0S160 78.8 160 176c0 18.7 2.9 36.8 8.3 53.7L7 391c-4.5 4.5-7 10.6-7 17v80c0 13.3 10.7 24 24 24h80c13.3 0 24-10.7 24-24V448h40c13.3 0 24-10.7 24-24V384h40c6.4 0 12.5-2.5 17-7l33.3-33.3c16.9 5.4 35 8.3 53.7 8.3zM376 96a40 40 0 1 1 0 80 40 40 0 1 1 0-80z"/></svg></div>
    <%= form.password_field :password, placeholder: 'Password', required: true %>
  </div>
  <br>
  <%= form.label :password_confirmation %>
  <div class="row">
    <div class="icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="30px"><path d="M336 352c97.2 0 176-78.8 176-176S433.2 0 336 0S160 78.8 160 176c0 18.7 2.9 36.8 8.3 53.7L7 391c-4.5 4.5-7 10.6-7 17v80c0 13.3 10.7 24 24 24h80c13.3 0 24-10.7 24-24V448h40c13.3 0 24-10.7 24-24V384h40c6.4 0 12.5-2.5 17-7l33.3-33.3c16.9 5.4 35 8.3 53.7 8.3zM376 96a40 40 0 1 1 0 80 40 40 0 1 1 0-80z"/></svg></div>
    <%= form.password_field :password_confirmation, placeholder: 'Confirm Password', required: true %>
  </div>
  <br>
  <button type="submit">Sign Up</button>
  <%= link_to root_path do %>
    <button type="button">GoTo Home</button>
  <% end %>
  
  <br>
  <%= link_to 'Already Have Acount? Login', login_path %>
<% end %>
</body>
</html>

app/views/users/show.html.erb
<%= render partial: 'partials/header' %>
<h1>This Is Home Page</h1>